# Generated by Django 2.2.10 on 2020-04-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devozoo', '0003_auto_20200415_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='category',
        ),
        migrations.AddField(
            model_name='dataset',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Dataset', to='devozoo.DatasetCategory', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
